name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_tdCVpvSteWKP2th50AFFHTYn
          vercel-project-id: prj_xem3S99lGlPXRziMVtNMDHpm96r9
          vercel-args: '--prod'
